// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACpH3XdM-f1fw_wI6nXKN61UM1GVifdnY',
    appId: '1:681783295895:web:7faaac8c19b1c538514ed2',
    messagingSenderId: '681783295895',
    projectId: 'stock-5961c',
    authDomain: 'stock-5961c.firebaseapp.com',
    databaseURL: 'https://stock-5961c-default-rtdb.firebaseio.com',
    storageBucket: 'stock-5961c.appspot.com',
    measurementId: 'G-4FSRXH60B4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoXMFrc7jcWRaYAqi47NAa6yin7Z2yB0k',
    appId: '1:681783295895:android:44420d9b8af32133514ed2',
    messagingSenderId: '681783295895',
    projectId: 'stock-5961c',
    databaseURL: 'https://stock-5961c-default-rtdb.firebaseio.com',
    storageBucket: 'stock-5961c.appspot.com',
  );
}
